name: Tests deploy

on:
   push:
     branches:
       - "**"
       - "!v*"
     tags-ignore:
       - "**"

jobs:
  test-standalone-charts:
    runs-on: ubuntu-latest
    steps:
      - run: kubectl cluster-info
      - run: kubectl version
      - run: kubectl get pods -n kube-system
      - run: kubectl create ns test-project-ci
