name: 👀 Review
on:
  push:
    branches:
      - "**"
      - "!master"
      - "!main"
      - "!feat/**"
      - "!fix/**"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  test:
    name: "job2"
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  kontinuous:
    uses: socialgouv/workflows/.github/workflows/use-ks-wh-review.yaml@v1
    secrets: inherit
