name: 😎 test_github_action
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "main"
    tags-ignore:
      - v*
jobs:
  test_github:
    runs-on: ubuntu-latest
    steps:
      - name: List of the GitHub Actions environment variables on Windows
        run: env
